# frozen_string_literal: true

# SawSew is our namespace in the application
module SawSew
  # pip events store AI responses, the prompts that generated them, and any task ids associated with them
  # they are generated by user credit transactions
  # there are almost no validations as we want to record the raw data
  # and check that the user credit transaction has the correct amount
  # for example, an amount of 0 for a failed event
  class PipEvent < ApplicationRecord
    # we've prefixed the table name with the namespace name
    # to avoid potential conflicts with other tables in the database
    self.table_name = 'sawsew_pip_events'

    has_one :user_credit_transaction,
            as: :originator,
            class_name: 'SawSew::UserCreditTransaction'

    alias_attribute :transaction, :user_credit_transaction
  end
end
